<?php
return [
	'DEFAULT_SUPERADMIN_PASSWORD' => 'Developer@123',
	'DEFAULT_ADMIN_PASSWORD' => 'Admin@123',
	'DEFAULT_MEMBER_PASSWORD' => 'Member@123',
	'CREATE_RECORD_STATUS_CODE' => 201,
	'SYSTEM_ERROR_STATUS_CODE' => 500,
];